(define x 100)
(let ((x 2)(y 3)) (display(+ x y)) (display " ") (display(* x y)))
(define eat (lambda(x) (if (equal? x "zao") (display "\nbreakfast")) (if (equal? x "zhong") (display "\nlunch"))))
(eat "zao")
(eat "zhong")
(define a 10)
(define b 20)
(define c 40)
(let ((g (* 3 a))) (+ (- g b) (+ g b)))
(let ((L (list a b c))) (cons (car L) (cdr L)))
(let ((x 9))
  (* x
     (let ((x (/ x 3)))
       (+ x x))))